### ISSUE TITLE
Bottom bar doesn't show on warnings

### ISSUE THREAD

**Issue by bfedie518** [rainlizard/ScriptNameOnTop#4]
The bottom bar pops up when you have an error, but it doesn't show if you have a warning.
![image](https://user-images.githubusercontent.com/17280776/200563238-fd2eb8b6-1842-43f2-902c-24fbbff49976.png)

**Comment by rainlizard** [comment]
https://github.com/rainlizard/ScriptNameOnTop/commit/ebcea2872d4dcb16977a5146107220d4883c1bfd
I've added a constant for it, set `WARNINGS_SHOW_BOTTOM_BAR` to true. But I wouldn't use this myself since warnings are already present in the debugger and this just causes the bottom bar to constantly be visible for those who only clear out all the warnings once in a blue moon.

**Comment by bfedie518** [comment]
Thanks.  I like having these pop up as I'm writing the code, not just when it runs.
